plugins {
    id 'java'
    id 'maven-publish'
}

group = 'com.danya'
version = '1.0-SNAPSHOT'

java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21

repositories {
    mavenCentral()
}

dependencies {
}

publishing {
    publications {
        maven (MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            url = "file://${project.projectDir.toString()}/maven-repo/"
        }
    }
}

